import type { Product } from "./products";

/**
 * Cele 22 de produse individuale (grosime|lățime×lungime fixă) din catalogul
 * furnizorului (foliepvctransparenta.ro/catalog/folie-transparenta-cristal-flex®-38),
 * scrapate iul. 2026. Fiecare produs are un preț fix (nu configurabil) — vezi
 * și produsul combo din lib/products.ts pentru varianta cu selectoare.
 */
export const cristalFlexCatalog: Product[] = [
  {
    slug: "folie-cristal-flex-1-0mm-1-5mx10m",
    categorySlug: "folii-transparente-terase",
    name: "1.0 mm | 1.5 m x 10 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 1000",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 1.0 mm | 1.50 m × 10 m.",
    price: 587.2,
    priceBeforeDiscount: 587.2,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["1.0 mm"],
    widths: ["1.50 m"],
    lengths: ["10 m"],
    sku: "CF100015010",
    weight: "21 kg",
    hasCart: true,
    variants: [{ thickness: "1.0 mm", width: "1.50 m", length: "10 m", price: 587.2 }],
    images: [
      "/products/cristal-flex-catalog/01.jpg",
      "/products/cristal-flex-catalog/02.jpg",
      "/products/cristal-flex-catalog/03.jpg",
      "/products/cristal-flex-catalog/04.jpg",
      "/products/cristal-flex-catalog/05.jpg",
      "/products/cristal-flex-catalog/06.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 1000, grosime 1.0 mm — varianta cea mai rigidă și rezistentă din gamă, recomandată pentru panouri fixe sau zone expuse la vânt.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 1.50 m e potrivită pentru deschideri standard de terasă sau foișor. Lungime potrivită pentru proiecte mici și medii, fără risipă de material.",
    ],
    useCases: [
      "Recomandată pentru zone expuse la vânt puternic sau pentru panouri fixe.",
      "Rola cântărește aproximativ 21 kg, ușor de manevrat de o singură persoană.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-2mx10m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 2.0 m x 10 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 2.00 m × 10 m.",
    price: 550.63,
    priceBeforeDiscount: 550.63,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["2.00 m"],
    lengths: ["10 m"],
    sku: "CF80020010-",
    weight: "29.5 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "2.00 m", length: "10 m", price: 550.63 }],
    images: [
      "/products/cristal-flex-catalog/07.jpg",
      "/products/cristal-flex-catalog/02.jpg",
      "/products/cristal-flex-catalog/08.jpg",
      "/products/cristal-flex-catalog/04.jpg",
      "/products/cristal-flex-catalog/05.jpg",
      "/products/cristal-flex-catalog/06.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.00 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime potrivită pentru proiecte mici și medii, fără risipă de material.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 29.5 kg, ușor de manevrat de o singură persoană.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-5mm-1-5mx10m",
    categorySlug: "folii-transparente-terase",
    name: "0.5 mm | 1.5 m x 10 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 500",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.5 mm | 1.50 m × 10 m.",
    price: 309.83,
    priceBeforeDiscount: 309.83,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.5 mm"],
    widths: ["1.50 m"],
    lengths: ["10 m"],
    sku: "CF50015010-",
    weight: "16 kg",
    hasCart: true,
    variants: [{ thickness: "0.5 mm", width: "1.50 m", length: "10 m", price: 309.83 }],
    images: [
      "/products/cristal-flex-catalog/09.jpg",
      "/products/cristal-flex-catalog/10.jpg",
      "/products/cristal-flex-catalog/11.jpg",
      "/products/cristal-flex-catalog/12.jpg",
      "/products/cristal-flex-catalog/13.jpg",
      "/products/cristal-flex-catalog/14.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 500, grosime 0.5 mm — varianta flexibilă și accesibilă din gamă, potrivită pentru închideri temporare sau zone adăpostite de vânt puternic.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 1.50 m e potrivită pentru deschideri standard de terasă sau foișor. Lungime potrivită pentru proiecte mici și medii, fără risipă de material.",
    ],
    useCases: [
      "Recomandată pentru pergole mici sau zone adăpostite, cu deschidere frecventă.",
      "Rola cântărește aproximativ 16 kg, ușor de manevrat de o singură persoană.",
    ],
  },
  {
    slug: "folie-cristal-flex-1-0mm-2mx10m",
    categorySlug: "folii-transparente-terase",
    name: "1.0 mm | 2.0 m x 10 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 1000",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 1.0 mm | 2.00 m × 10 m.",
    price: 782.94,
    priceBeforeDiscount: 782.94,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["1.0 mm"],
    widths: ["2.00 m"],
    lengths: ["10 m"],
    sku: "CF100020010",
    weight: "21 kg",
    hasCart: true,
    variants: [{ thickness: "1.0 mm", width: "2.00 m", length: "10 m", price: 782.94 }],
    images: [
      "/products/cristal-flex-catalog/15.jpg",
      "/products/cristal-flex-catalog/16.jpg",
      "/products/cristal-flex-catalog/17.jpg",
      "/products/cristal-flex-catalog/18.jpg",
      "/products/cristal-flex-catalog/19.jpg",
      "/products/cristal-flex-catalog/20.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 1000, grosime 1.0 mm — varianta cea mai rigidă și rezistentă din gamă, recomandată pentru panouri fixe sau zone expuse la vânt.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.00 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime potrivită pentru proiecte mici și medii, fără risipă de material.",
    ],
    useCases: [
      "Recomandată pentru zone expuse la vânt puternic sau pentru panouri fixe.",
      "Rola cântărește aproximativ 21 kg, ușor de manevrat de o singură persoană.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-2-6mx15m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 2.60 m x 15 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 2.60 m × 15 m.",
    price: 1391.16,
    priceBeforeDiscount: 1391.16,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["2.60 m"],
    lengths: ["15 m"],
    sku: "CF80026015-",
    weight: "40.2 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "2.60 m", length: "15 m", price: 1391.16 }],
    images: [
      "/products/cristal-flex-catalog/21.jpg",
      "/products/cristal-flex-catalog/22.jpg",
      "/products/cristal-flex-catalog/23.jpg",
      "/products/cristal-flex-catalog/24.jpg",
      "/products/cristal-flex-catalog/25.jpg",
      "/products/cristal-flex-catalog/26.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.60 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime medie, un echilibru bun între suprafața acoperită și ușurința manipulării rolei.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 40.2 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-2mx15m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 2.0 m x 15 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 2.00 m × 15 m.",
    price: 825.95,
    priceBeforeDiscount: 825.95,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["2.00 m"],
    lengths: ["15 m"],
    sku: "CF80020015-",
    weight: "38 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "2.00 m", length: "15 m", price: 825.95 }],
    images: [
      "/products/cristal-flex-catalog/27.jpg",
      "/products/cristal-flex-catalog/16.jpg",
      "/products/cristal-flex-catalog/28.jpg",
      "/products/cristal-flex-catalog/29.jpg",
      "/products/cristal-flex-catalog/19.jpg",
      "/products/cristal-flex-catalog/20.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.00 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime medie, un echilibru bun între suprafața acoperită și ușurința manipulării rolei.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 38 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-2-2mx15m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 2.20 m x 15 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 2.20 m × 15 m.",
    price: 1177.14,
    priceBeforeDiscount: 1177.14,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["2.20 m"],
    lengths: ["15 m"],
    sku: "CF80022015-",
    weight: "34 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "2.20 m", length: "15 m", price: 1177.14 }],
    images: [
      "/products/cristal-flex-catalog/30.jpg",
      "/products/cristal-flex-catalog/31.jpg",
      "/products/cristal-flex-catalog/32.jpg",
      "/products/cristal-flex-catalog/33.jpg",
      "/products/cristal-flex-catalog/34.jpg",
      "/products/cristal-flex-catalog/35.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.20 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime medie, un echilibru bun între suprafața acoperită și ușurința manipulării rolei.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 34 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-2-2mx30m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 2.20 m x 30 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 2.20 m × 30 m.",
    price: 2130.93,
    priceBeforeDiscount: 2130.93,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["2.20 m"],
    lengths: ["30 m"],
    sku: "CF80022030-",
    weight: "66 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "2.20 m", length: "30 m", price: 2130.93 }],
    images: [
      "/products/cristal-flex-catalog/21.jpg",
      "/products/cristal-flex-catalog/36.jpg",
      "/products/cristal-flex-catalog/23.jpg",
      "/products/cristal-flex-catalog/24.jpg",
      "/products/cristal-flex-catalog/25.jpg",
      "/products/cristal-flex-catalog/26.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.20 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime mare, recomandată pentru proiecte extinse — mai puține îmbinări pe suprafețe ample.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 66 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-1-37mx30m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 1.37 m x 30 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 1.37 m × 30 m.",
    price: 1070.12,
    priceBeforeDiscount: 1070.12,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["1.37 m"],
    lengths: ["30 m"],
    sku: "CF80015037-",
    weight: "44.5 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "1.37 m", length: "30 m", price: 1070.12 }],
    images: [
      "/products/cristal-flex-catalog/37.jpg",
      "/products/cristal-flex-catalog/38.jpg",
      "/products/cristal-flex-catalog/39.jpg",
      "/products/cristal-flex-catalog/40.jpg",
      "/products/cristal-flex-catalog/41.jpg",
      "/products/cristal-flex-catalog/42.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 1.37 m e potrivită pentru deschideri standard de terasă sau foișor. Lungime mare, recomandată pentru proiecte extinse — mai puține îmbinări pe suprafețe ample.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 44.5 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-2-6mx30m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 2.60 m x 30 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 2.60 m × 30 m.",
    price: 2622.85,
    priceBeforeDiscount: 2622.85,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["2.60 m"],
    lengths: ["30 m"],
    sku: "CF80026030-",
    weight: "78 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "2.60 m", length: "30 m", price: 2622.85 }],
    images: [
      "/products/cristal-flex-catalog/43.jpg",
      "/products/cristal-flex-catalog/44.jpg",
      "/products/cristal-flex-catalog/45.jpg",
      "/products/cristal-flex-catalog/46.jpg",
      "/products/cristal-flex-catalog/47.jpg",
      "/products/cristal-flex-catalog/48.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.60 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime mare, recomandată pentru proiecte extinse — mai puține îmbinări pe suprafețe ample.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 78 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-1-5mx10m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 1.5 m x 10 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 1.50 m × 10 m.",
    price: 495.13,
    priceBeforeDiscount: 495.13,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["1.50 m"],
    lengths: ["10 m"],
    sku: "CF80015010-",
    weight: "22 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "1.50 m", length: "10 m", price: 495.13 }],
    images: [
      "/products/cristal-flex-catalog/49.jpg",
      "/products/cristal-flex-catalog/50.jpg",
      "/products/cristal-flex-catalog/51.jpg",
      "/products/cristal-flex-catalog/52.jpg",
      "/products/cristal-flex-catalog/53.jpg",
      "/products/cristal-flex-catalog/54.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 1.50 m e potrivită pentru deschideri standard de terasă sau foișor. Lungime potrivită pentru proiecte mici și medii, fără risipă de material.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 22 kg, ușor de manevrat de o singură persoană.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-5mm-2mx15m",
    categorySlug: "folii-transparente-terase",
    name: "0.5 mm | 2.0 m x 15 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 500",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.5 mm | 2.00 m × 15 m.",
    price: 618.92,
    priceBeforeDiscount: 618.92,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.5 mm"],
    widths: ["2.00 m"],
    lengths: ["15 m"],
    sku: "CF50020015-",
    weight: "16 kg",
    hasCart: true,
    variants: [{ thickness: "0.5 mm", width: "2.00 m", length: "15 m", price: 618.92 }],
    images: [
      "/products/cristal-flex-catalog/55.jpg",
      "/products/cristal-flex-catalog/02.jpg",
      "/products/cristal-flex-catalog/03.jpg",
      "/products/cristal-flex-catalog/56.jpg",
      "/products/cristal-flex-catalog/57.jpg",
      "/products/cristal-flex-catalog/58.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 500, grosime 0.5 mm — varianta flexibilă și accesibilă din gamă, potrivită pentru închideri temporare sau zone adăpostite de vânt puternic.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.00 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime medie, un echilibru bun între suprafața acoperită și ușurința manipulării rolei.",
    ],
    useCases: [
      "Recomandată pentru pergole mici sau zone adăpostite, cu deschidere frecventă.",
      "Rola cântărește aproximativ 16 kg, ușor de manevrat de o singură persoană.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-5mm-2mx10m",
    categorySlug: "folii-transparente-terase",
    name: "0.5 mm | 2.0 m x 10 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 500",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.5 mm | 2.00 m × 10 m.",
    price: 412.61,
    priceBeforeDiscount: 412.61,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.5 mm"],
    widths: ["2.00 m"],
    lengths: ["10 m"],
    sku: "CF50020010-",
    weight: "16 kg",
    hasCart: true,
    variants: [{ thickness: "0.5 mm", width: "2.00 m", length: "10 m", price: 412.61 }],
    images: [
      "/products/cristal-flex-catalog/59.jpg",
      "/products/cristal-flex-catalog/50.jpg",
      "/products/cristal-flex-catalog/51.jpg",
      "/products/cristal-flex-catalog/52.jpg",
      "/products/cristal-flex-catalog/60.jpg",
      "/products/cristal-flex-catalog/54.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 500, grosime 0.5 mm — varianta flexibilă și accesibilă din gamă, potrivită pentru închideri temporare sau zone adăpostite de vânt puternic.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.00 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime potrivită pentru proiecte mici și medii, fără risipă de material.",
    ],
    useCases: [
      "Recomandată pentru pergole mici sau zone adăpostite, cu deschidere frecventă.",
      "Rola cântărește aproximativ 16 kg, ușor de manevrat de o singură persoană.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-2mx30m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 2.0 m x 30 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 2.00 m × 30 m.",
    price: 1617.17,
    priceBeforeDiscount: 1617.17,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["2.00 m"],
    lengths: ["30 m"],
    sku: "CF80020030-",
    weight: "63.6 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "2.00 m", length: "30 m", price: 1617.17 }],
    images: [
      "/products/cristal-flex-catalog/37.jpg",
      "/products/cristal-flex-catalog/38.jpg",
      "/products/cristal-flex-catalog/32.jpg",
      "/products/cristal-flex-catalog/61.jpg",
      "/products/cristal-flex-catalog/62.jpg",
      "/products/cristal-flex-catalog/35.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.00 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime mare, recomandată pentru proiecte extinse — mai puține îmbinări pe suprafețe ample.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 63.6 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-1-5mx30m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 1.5 m x 30 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 1.50 m × 30 m.",
    price: 1170.4,
    priceBeforeDiscount: 1170.4,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["1.50 m"],
    lengths: ["30 m"],
    sku: "CF80015030-",
    weight: "47.6 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "1.50 m", length: "30 m", price: 1170.4 }],
    images: [
      "/products/cristal-flex-catalog/27.jpg",
      "/products/cristal-flex-catalog/16.jpg",
      "/products/cristal-flex-catalog/17.jpg",
      "/products/cristal-flex-catalog/63.jpg",
      "/products/cristal-flex-catalog/64.jpg",
      "/products/cristal-flex-catalog/65.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 1.50 m e potrivită pentru deschideri standard de terasă sau foișor. Lungime mare, recomandată pentru proiecte extinse — mai puține îmbinări pe suprafețe ample.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 47.6 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-5mm-1-5mx50m",
    categorySlug: "folii-transparente-terase",
    name: "0.5 mm | 1.5 m x 50 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 500",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.5 mm | 1.50 m × 50 m.",
    price: 1361.25,
    priceBeforeDiscount: 1587.24,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.5 mm"],
    widths: ["1.50 m"],
    lengths: ["50 m"],
    sku: "CF50015050-",
    weight: "35 kg",
    hasCart: true,
    variants: [{ thickness: "0.5 mm", width: "1.50 m", length: "50 m", price: 1361.25, oldPrice: 1587.24 }],
    images: [
      "/products/cristal-flex-catalog/66.jpg",
      "/products/cristal-flex-catalog/10.jpg",
      "/products/cristal-flex-catalog/11.jpg",
      "/products/cristal-flex-catalog/67.jpg",
      "/products/cristal-flex-catalog/68.jpg",
      "/products/cristal-flex-catalog/69.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 500, grosime 0.5 mm — varianta flexibilă și accesibilă din gamă, potrivită pentru închideri temporare sau zone adăpostite de vânt puternic.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 1.50 m e potrivită pentru deschideri standard de terasă sau foișor. Lungime maximă din gamă, ideală pentru comenzi mari sau instalatori care lucrează pe mai multe șantiere.",
    ],
    useCases: [
      "Recomandată pentru pergole mici sau zone adăpostite, cu deschidere frecventă.",
      "Rola cântărește aproximativ 35 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-2-4mx30m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 2.40 m x 30 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 2.40 m × 30 m.",
    price: 2568.3,
    priceBeforeDiscount: 2568.3,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["2.40 m"],
    lengths: ["30 m"],
    sku: "CF80024030-",
    weight: "72.8 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "2.40 m", length: "30 m", price: 2568.3 }],
    images: [
      "/products/cristal-flex-catalog/70.jpg",
      "/products/cristal-flex-catalog/71.jpg",
      "/products/cristal-flex-catalog/45.jpg",
      "/products/cristal-flex-catalog/46.jpg",
      "/products/cristal-flex-catalog/72.jpg",
      "/products/cristal-flex-catalog/73.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.40 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime mare, recomandată pentru proiecte extinse — mai puține îmbinări pe suprafețe ample.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 72.8 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-2-4mx15m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 2.40 m x 15 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 2.40 m × 15 m.",
    price: 1284.15,
    priceBeforeDiscount: 1284.15,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["2.40 m"],
    lengths: ["15 m"],
    sku: "CF80024015-",
    weight: "37.1 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "2.40 m", length: "15 m", price: 1284.15 }],
    images: [
      "/products/cristal-flex-catalog/43.jpg",
      "/products/cristal-flex-catalog/44.jpg",
      "/products/cristal-flex-catalog/45.jpg",
      "/products/cristal-flex-catalog/46.jpg",
      "/products/cristal-flex-catalog/47.jpg",
      "/products/cristal-flex-catalog/48.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 2.40 m permite acoperirea unor deschideri largi fără cusături laterale. Lungime medie, un echilibru bun între suprafața acoperită și ușurința manipulării rolei.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 37.1 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-1-8mx30m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 1.80 m x 30 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 1.80 m × 30 m.",
    price: 1455.45,
    priceBeforeDiscount: 1455.45,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["1.80 m"],
    lengths: ["30 m"],
    sku: "CF80018030-",
    weight: "60 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "1.80 m", length: "30 m", price: 1455.45 }],
    images: [
      "/products/cristal-flex-catalog/74.jpg",
      "/products/cristal-flex-catalog/75.jpg",
      "/products/cristal-flex-catalog/23.jpg",
      "/products/cristal-flex-catalog/76.jpg",
      "/products/cristal-flex-catalog/77.jpg",
      "/products/cristal-flex-catalog/26.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 1.80 m e potrivită pentru deschideri standard de terasă sau foișor. Lungime mare, recomandată pentru proiecte extinse — mai puține îmbinări pe suprafețe ample.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 60 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-8mm-1-5mx15m",
    categorySlug: "folii-transparente-terase",
    name: "0.8 mm | 1.5 m x 15 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 800",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.8 mm | 1.50 m × 15 m.",
    price: 742.68,
    priceBeforeDiscount: 742.68,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.8 mm"],
    widths: ["1.50 m"],
    lengths: ["15 m"],
    sku: "CF80015015-",
    weight: "29.1 kg",
    hasCart: true,
    variants: [{ thickness: "0.8 mm", width: "1.50 m", length: "15 m", price: 742.68 }],
    images: [
      "/products/cristal-flex-catalog/07.jpg",
      "/products/cristal-flex-catalog/02.jpg",
      "/products/cristal-flex-catalog/03.jpg",
      "/products/cristal-flex-catalog/56.jpg",
      "/products/cristal-flex-catalog/78.jpg",
      "/products/cristal-flex-catalog/58.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 800, grosime 0.8 mm — cel mai folosit standard pentru terase, foișoare și spații comerciale, cu un echilibru bun între flexibilitate și rezistență.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 1.50 m e potrivită pentru deschideri standard de terasă sau foișor. Lungime medie, un echilibru bun între suprafața acoperită și ușurința manipulării rolei.",
    ],
    useCases: [
      "Recomandată pentru terase, foișoare și restaurante — echilibru optim între flexibilitate și rigiditate.",
      "Rola cântărește aproximativ 29.1 kg, ușor de manevrat de o singură persoană.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-5mm-1-5mx30m",
    categorySlug: "folii-transparente-terase",
    name: "0.5 mm | 1.5 m x 30 m - Folie transparenta pentru inchidere terasa, foisor - Cristal Flex® 500",
    shortDescription: "Folie PVC transparentă Cristal Flex®, 0.5 mm | 1.50 m × 30 m.",
    price: 928.35,
    priceBeforeDiscount: 928.35,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.5 mm"],
    widths: ["1.50 m"],
    lengths: ["30 m"],
    sku: undefined,
    weight: "35 kg",
    hasCart: true,
    variants: [{ thickness: "0.5 mm", width: "1.50 m", length: "30 m", price: 928.35 }],
    images: [
      "/products/cristal-flex-catalog/79.jpg",
      "/products/cristal-flex-catalog/80.jpg",
      "/products/cristal-flex-catalog/81.jpg",
      "/products/cristal-flex-catalog/82.jpg",
      "/products/cristal-flex-catalog/83.jpg",
      "/products/cristal-flex-catalog/84.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex® 500, grosime 0.5 mm — varianta flexibilă și accesibilă din gamă, potrivită pentru închideri temporare sau zone adăpostite de vânt puternic.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 1.50 m e potrivită pentru deschideri standard de terasă sau foișor. Lungime mare, recomandată pentru proiecte extinse — mai puține îmbinări pe suprafețe ample.",
    ],
    useCases: [
      "Recomandată pentru pergole mici sau zone adăpostite, cu deschidere frecventă.",
      "Rola cântărește aproximativ 35 kg — recomandăm manipularea de către două persoane la instalare.",
    ],
  },
  {
    slug: "folie-cristal-flex-0-5mm-1-8mx30m-ignifugata",
    categorySlug: "folii-transparente-terase",
    name: "0.5 mm | 1.8 m x 30 m - Folie transparentă ignifugată pentru închidere terasă și foișoare Cristal Flex®, grosime 0,5 mm",
    shortDescription: "Folie PVC transparentă ignifugată, 0.5 mm | 1.80 m × 30 m.",
    price: 1185.92,
    priceBeforeDiscount: 1185.92,
    priceUnit: "RON / rolă (TVA inclus)",
    thicknesses: ["0.5 mm"],
    widths: ["1.80 m"],
    lengths: ["30 m"],
    sku: "CF50018030FR",
    weight: undefined,
    hasCart: true,
    variants: [{ thickness: "0.5 mm", width: "1.80 m", length: "30 m", price: 1185.92 }],
    images: [
      "/products/cristal-flex-catalog/85.jpg",
      "/products/cristal-flex-catalog/86.jpg",
      "/products/cristal-flex-catalog/09.jpg",
      "/products/cristal-flex-catalog/87.jpg",
      "/products/cristal-flex-catalog/88.jpg",
    ],
    description: [
      "Folie PVC transparentă Cristal Flex®, tratată ignifug — aceleași proprietăți de claritate și rezistență ale foliei standard, cu tratament suplimentar de întârziere a arderii, potrivită pentru spații comerciale unde normele PSI impun materiale ignifugate.",
      "Claritate optică ridicată, aspect de sticlă, complet impermeabilă și tratată anti-UV pentru o durabilitate mai mare la expunere îndelungată la soare.",
      "Lățimea de 1.80 m e potrivită pentru deschideri standard de terasă sau foișor. Lungime mare, recomandată pentru proiecte extinse — mai puține îmbinări pe suprafețe ample.",
    ],
    useCases: [
      "Recomandată pentru spații comerciale sau publice unde e necesar un material cu tratament ignifug.",
    ],
  },
];
